W5D1/music_app_project/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:new, :create, :destroy]
  resources :bands
end

W5D1/music_app_project/music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  band_id    :integer          not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :title, presence: true, uniqueness: true

end

W5D1/music_app_project/music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  
end

W5D1/music_app_project/music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6 }, allow_nil: true
  before_validation :ensure_session_token

  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end
end

W5D1/music_app_project/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    current_user != nil
  end

  def log_in_user!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

end

W5D1/music_app_project/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url(@band)
    else
      flash[:errors] = ["Name can't be blank"]
      redirect_to bands_url
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] << "Could not edit band"
      redirect_to edit_band_url
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])

    @band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

W5D1/music_app_project/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # def create
  #   session[:session_token] = current_user.reset_session_token!
  # end

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user.nil?
      flash[:errors] = ["Invalid login information"]
      redirect_to new_sessions_url
    else
      log_in_user!(@user)
      redirect_to bands_url
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_sessions_url
  end
end

W5D1/music_app_project/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)
      redirect_to bands_url
    else
      flash.now[:errors] = ["Invalid email and/or password"]
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end


  private
  def user_params
    params.require(:user).permit(:email, :password, :session_token)
  end
end

W5D1/music_app_project/music_app/app/helpers/application_helper.rb
module ApplicationHelper

  def token_auth
    "<input type='hidden' name='authenticity_token' value=#{form_authenticity_token}>".html_safe
  end


end

W5D1/music_app_project/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W5D1/music_app_project/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W5D1/music_app_project/music_app/app/helpers/users_helper.rb
module UsersHelper
end

W5D1/music_app_project/music_app/app/views/bands/edit.html.erb
<h2>EDIT <%= @band.name.upcase %></h2>

<form action="<%= band_url(@band) %>" method="post">
  <%= token_auth %>
  <input type="hidden" name="_method" value="PATCH">

  <label for="name">Name</label>
  <input id="name" type="text" name="band[name]" value="">
  <input type="submit" value="Submit">

</form>

W5D1/music_app_project/music_app/app/views/bands/index.html.erb
<h1>Bands</h1>

<ul>
<% @bands.each do |band| %>
  <li><a href="<%= band_url(band) %>"><%= band.name %></a></li>
<% end %>
</ul>

<footer>
  <a class="likeabutton" href=" <%= new_band_url %>">New band</a>
</footer>

W5D1/music_app_project/music_app/app/views/bands/new.html.erb
<h2>NEW BAND</h2>

<form action="<%= bands_url %>" method="post">
  <%= token_auth %>

  <label for="name">Name</label>
  <input id="name" type="text" name="band[name]" value="">
  <input type="submit" value="Submit">
</form>

W5D1/music_app_project/music_app/app/views/bands/show.html.erb
<h1> <%= @band.name %> </h1>

<h2>ALBUMS</h2>

<a class="likeabutton" href=" <%= edit_band_url(@band) %>">EDIT</a>
<form action=" <%= band_url %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Delete Band">
</form>

W5D1/music_app_project/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>

      .likeabutton {
        appearance: button;
        -moz-appearance: button;
        -webkit-appearance: button;
        text-decoration: none; font: menu; color: black;
        display: inline-block; padding: 2px 8px;
      }

      .title {
        font-size: 50px;
        font-style: italic;
        text-align: center;
      }

      body {
        background-color: lightblue;
      }



    </style>
  </head>

  <h1 class='title'>MUSIC APP</h1>
  <a class="likeabutton" href="<%= bands_url %>">Take me Home</a>
  <br>

  <% if current_user %>
    <div>
        <p>Logged in as: <%= current_user.email %></p>
        <form action="<%= sessions_url %>" method="post">
          <input type="hidden" name="_method" value="delete">

          <input type="submit" value="Sign Out">
        </form>
    </div>
  <% else %>
      <a class="likeabutton" href=" <%= new_user_url %> ">Go to Sign-up!</a>
      <a class="likeabutton" href="<%= new_sessions_url %>">Sign In</a>
  <% end %>

  <br><br>

  <body>
    <%= yield %>
  </body>
</html>

W5D1/music_app_project/music_app/app/views/users/new.html.erb
<h2>SIGN UP</h2>

<form action="<%= users_url %>" method="post">
  <%= token_auth %>

  <label for="email">Email</label>
  <input type="text" name="user[email]">

  <label for="password">Password</label>
  <input type="password" name="user[password]">

  <input type="submit" value="Submit">
</form>